# Deploy everything except the jbuild.py and edctl.py scripts, useful when
# developing.
#   icos ganymede jbuild -ejbuild_force=false
#
# Deploy new users, keys, edctl and rsync.
#   icos ganymede jbuild_users jbuild_rsync

- hosts: ganymede_host
  vars:
    # These variable are prefixed with 'jupyter_' instead of 'ganymede_' so
    # that we can reuse files/jupyter.conf without change.
    jupyter_ip: "{{ _lxd.addresses.eth0 | first }}"
    jupyter_domains:
      - ganymede.icos-cp.eu
  vars_files:
    - vault.yml
  pre_tasks:
    - import_role: name=icos.zfsdocker
      tags:
        - zfs
        - zfsdocker
      vars:
        zfsdocker_name: ganymede
        zfsdocker_size: "100G"

    - name: Create the ganymede container
      tags:
        - lxd
        - forward
        - nginx
      lxd_container:
        name: ganymede
        state: started
        profiles:
          - default
          - ssh_root
        source:
          type: image
          mode: pull
          server: https://cloud-images.ubuntu.com/releases
          protocol: simplestreams
          alias: "20.04"
        devices:
          root:
            path: "/"
            pool: "default"
            type: "disk"
            size: "50GB"
          docker:
            path: /var/lib/docker
            source: "{{ zfsdocker_zvol }}"
            type: disk
            raw.mount.options: user_subvol_rm_allowed
          data:
            path: /data
            source: /data
            type: disk
            recursive: "yes"
        config:
          security.nesting: "true"
        wait_for_ipv4_addresses: true
        wait_for_ipv4_interfaces: eth0
        timeout: 60
      register: _lxd

  roles:
    - role: icos.lxd_forward
      tags: forward
      lxd_forward_ip: "{{ jupyter_ip }}"
      lxd_forward_name: ganymede

    - role: icos.certbot2
      tags: cert
      certbot_name: ganymede
      certbot_domains: "{{ jupyter_domains }}"

    - role: icos.nginxsite
      tags: nginx
      nginxsite_name: ganymede
      nginxsite_file: files/jupyter.conf
      jupyter_domain: "{{ jupyter_domains | first }}"
      jupyter_cert_name: ganymede
      jupyter_port: 8000


- hosts: ganymede
  vars_files:
    - vars.yml
    - vault.yml
  handlers:
    - name: reload sshd
      systemd:
        name: sshd
        state: reloaded

  roles:
    - role: icos.lxd_guest
      tags: guest

    - role: icos.python3
      tags: python3

    - role: icos.docker
      tags: docker
      docker_periodic_cleanup: True

    - role: icos.superuser
      tags: users
      superuser_list: "{{ vault_ganymede_superusers }}"
      superuser_disable_coredump: true

    - role: icos.jupyter
      tags: jupyter
      jupyter_admins: "{{ vault_ganymede_admins }}"

    - role: icos.jbuild
      tags: jbuild
      jbuild_users: "{{ vault_ganymede_jbuild_users }}"
      jbuild_registry_pass: "{{ vault_registry_pass }}"
      jbuild_edctl_host: exploredata
      jbuild_edctl_host_name: exploredata.lxd
      jbuild_edctl_host_port: 22
      jbuild_rsync_host: jupyter
      jbuild_rsync_host_port: 22
      jbuild_rsync_host_name: jupyter.lxd
      jbuild_jyctl_host: jupyter
      jbuild_jyctl_host_port: 22
      jbuild_jyctl_host_name: jupyter.lxd

  tasks:
    - tags: sshlogin
      include_role:
        name: icos.sshlogin
        apply:
          tags: sshlogin
      vars:
        sshlogin_dst: "{{ login.dst }}"
        sshlogin_src_user: "{{ login.src_user }}"
        sshlogin_dst_user: "{{ login.dst_user }}"
        sshlogin_src_dst_host: "{{ login.dst_host }}"
        sshlogin_src_dst_port: "{{ login.dst_port }}"
      loop: "{{ vault_ganymede_sshlogins }}"
      loop_control:
        loop_var: login
