---
# Version check play.
# Not that it'll work properly - https://github.com/ansible/ansible/issues/18375
- hosts: all
  gather_facts: no
  pre_tasks:
    - name: Ansible version check
      assert:
        that: "ansible_version.full | version_compare('2.2', '>=')"
        msg: >
          "This playbook uses features that requires ansible >= 2.2"

# The system that is being provisioned needs to have python installed. Of the
# two systems we currently support, CentOS 7 and Ubuntu 16.04, only CentOS have
# python installed out of the box. This play will attempt to blindly install
# python on Ubuntu. The play needs to have gather_facts turned off, because
# gather_facts requires python to be already installed.
- hosts: all
  become: true
  gather_facts: no
  pre_tasks:
    - name: install python (required by ansible)
      # http://docs.ansible.com/ansible/intro_installation.html
      raw: "test -e /usr/bin/python || apt install -y python-minimal"
      

- include: icosprod.yml
- include: stilt.yml    
