Vagrant.configure("2") do |config|

  config.ssh.insert_key = false
  config.vm.provider :virtualbox do |v|
    v.memory = 2048
    v.linked_clone = true
  end

  # CENTOS/7
  config.vm.define "centos" do |inventory|
    inventory.vm.box = "centos/7"
    inventory.vm.box_version = "1803.01"
    inventory.vm.hostname = "centos"
    inventory.vm.network "private_network", ip: "192.168.99.10"
    inventory.vm.synced_folder ".", "/vagrant", disabled: true
  end
  
  # UBUNTU 18.04
  config.vm.define "bionic" do |inventory|
    inventory.ssh.insert_key = true
    inventory.vm.box = "ubuntu/bionic64"
    inventory.vm.hostname = "ubuntu-bionic"
    inventory.vm.network "private_network", ip: "192.168.99.30"
    inventory.vm.synced_folder ".", "/vagrant", disabled: true    
  end

  # UBUNTU 18.04
  config.vm.define "bionid" do |inventory|
    inventory.ssh.insert_key = true
    inventory.vm.box = "ubuntu/bionic64"
    inventory.vm.hostname = "ubuntu-bionid"
    inventory.vm.network "private_network", ip: "192.168.99.40"
    inventory.vm.synced_folder ".", "/vagrant", disabled: true    
  end
  
end
