Vagrant.configure("2") do |config|

  config.ssh.insert_key = false
  config.vm.provider :virtualbox do |v|
    v.memory = 2048
    v.linked_clone = true
  end

  # CENTOS/7
  config.vm.define "centos" do |inventory|
    inventory.vm.box = "centos/7"
    inventory.vm.hostname = "centos"
    inventory.vm.network "private_network", ip: "192.168.99.10"
    inventory.vm.synced_folder ".", "/vagrant", disabled: true
  end
  
  # UBUNTU 16.04
  config.vm.define "ubuntu" do |inventory|
    inventory.ssh.insert_key = true
    inventory.vm.box = "ubuntu/xenial64"
    inventory.vm.hostname = "ubuntu"
    inventory.vm.network "private_network", ip: "192.168.99.20"
    inventory.vm.synced_folder ".", "/vagrant", disabled: true
  end
  
end
