- hosts: wordpress_host
  vars:
    wordpress_ip: "{{ _lxd.addresses.eth0 | first }}"
    wordpress_domains:
      - www.ingos-infrastructure.eu
      - www.eric-forum.eu
      - www.icos-summerschool.eu
      - www.envriplus.eu
  vars_files:
    - vault.yml
  tasks:
    - name: Create wordpress storage pool
      tags: pool
      shell: >-
        /snap/bin/lxc storage show wordpress > /dev/null 2>&1 ||
        /snap/bin/lxc storage create wordpress btrfs size=500GB
      register: _r
      changed_when:
        - '"Storage pool wordpress created" in _r.stdout'

    - name: Create the wordpress container
      tags:
        - lxd
        - nginx
        - forward
      lxd_container:
        name: wordpress
        state: started
        profiles:
          - default
          - ssh_root
        source:
          type: image
          mode: pull
          server: https://cloud-images.ubuntu.com/releases
          protocol: simplestreams
          alias: "18.04"
        config:
          limits.cpu: "2"
          limits.memory: "2GB"
        devices:
          root:
            path: /
            type: disk
            pool: wordpress
            size: "500GB"
        wait_for_ipv4_addresses: true
        timeout: 600
      register: _lxd

    - name: Forward port
      tags: forward
      import_role:
        name: icos.lxd_forward
      vars:
        lxd_forward_name: wordpress
        lxd_forward_ip: "{{ wordpress_ip }}"

    - name: Create certificate
      tags: cert
      import_role:
        name: icos.certbot2
      vars:
        certbot_name: wordpress
        certbot_domains: "{{ wordpress_domains }}"

    - name: Install nginx configuration
      tags: nginx
      import_role:
        name: icos.nginxsite
      vars:
        nginxsite_name: wordpress
        nginxsite_file: files/wordpress.conf


- hosts: wordpress
  vars:
    lxd_guest_root_keys: "{{ vault_wordpress_root_keys }}"
  vars_files:
    - vault.yml
  tasks:
    - import_role: name=icos.lxd_guest
      tags: guest

    - debug:
        msg: |
          # Don't forget to add the following in your wp-config.php, after the
          # WP_DEBUG line. Otherwise you'll get redirect loops.
          if ( $_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https' )
          {
              $_SERVER['HTTPS']       = 'on';
              $_SERVER['SERVER_PORT'] = 443;
          }
