#!/bin/bash
# List the CMD and ENTRYPOINT of the given object.

set -u
set -e

if [[ $# -eq 0 ]]; then
    echo "usage: docker-entrypoint <object>"
    exit 1
fi

if [[ $# -gt 0 ]]; then
    docker inspect --format \
'ENTRYPOINT:{{ range .Config.Entrypoint }} {{.}}{{ end }}
CMD:{{ range .Config.Cmd }} {{.}}{{ end }}' "$1"
fi


