<?php


function document_presenter_block_info() {
	$blocks = array();
	
	$blocks['document_presenter'] = array(
			'info' => t('Document presenter'),
	);

	return $blocks;
}


function document_presenter_block_view($delta = '') {

	if ($delta == 'document_presenter') {
	
		$block = array(
			'subject' => t(''),
			'content' => array(
				'#markup' => t(_document_presenter_output()),
				'#attached' => array(
					'css' => array(drupal_get_path('module', 'document_presenter') . '/document_presenter.css'),
					'js' => array(drupal_get_path('module', 'document_presenter') . '/document_presenter.js'),
				),
			),
		);
		
		return $block;	
	}
}


function document_presenter_menu() {
	$items = array();

	$items['admin/config/content/document_presenter'] = array(
		'title' => 'Document presenter configuration',
		'description' => 'Configuration for Document presenter',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('_document_presenter_form'),
		'access arguments' => array('access administration pages'),
		'type' => MENU_NORMAL_ITEM,
	);

	return $items;
}


function _document_presenter_form($form, &$form_state) {
	$options = array();

	$list = _document_presenter_options();
	foreach ($list as $key => $value) {
		$options[$value['path']] = t($value['name']);
	}

	$checked = array();
	foreach (variable_get('document_presenter_object_list') as $key => $value) {
		if ($value) {
			$checked[] = $value;
		}
	}

	$form['description'] = array(
		'#markup' => t('<span style="font-weight: 700">Mark or unmark the documents you want to add/remove for the Press and Media and then click on the button to save.</span>'),
	);

	$form['document_presenter_object_list'] = array(
		'#type' => 'checkboxes',
		'#description' => t(''),
		'#options' => $options,
		'#default_value' => $checked,
	);

	return system_settings_form($form);
}


function _document_presenter_options() {
	$content = array();

	$folder = variable_get('file_public_path', conf_path() . '/files');

	foreach (scandir($folder) as $file) {

		if ((is_file($folder . '/' . $file) && (substr_compare($file, 'pdf', -3, 3, true) == 0))) {
			$content[] = array('name' => $file, 'path' => $file);
		}
	}

	return $content;
}


function _document_presenter_output() {

	$folder = variable_get('file_public_path', conf_path() . '/files');

	$list = array();
	foreach (variable_get('document_presenter_object_list') as $key => $value) {
		if ($value && file_exists($folder . '/' .$value) && is_file($folder . '/' . $value)) {
			$list[] = _collect($value);
		}
	}

	$title_color = '';
	if (variable_get('broscience_style_contents_title_color')) {
		$title_color = 'style="color: ' . variable_get('broscience_style_contents_title_color') . '"';
	}

	$element_color = '';
	if (variable_get('broscience_style_contents_element_color')) {
		$element_color = 'background-color: ' . variable_get('broscience_style_contents_element_color') . '; color: #ffffff;';
	}

	$output = '<div class="block_title" ' . $title_color . '><h2>PRESS AND MEDIA</h2></div>';

	$output .= '<div id="document_presenter">';

	if (! empty($list)) {

		usort($list, _compare);

		$count = 1;
		$has_archive = false;

		foreach ($list as $file) {

			$pic_uri = '';
			if ($file['file_pic_uri']) {
				$pic_uri = '/' . $folder . '/' . str_replace('public://', '', $file['file_pic_uri']);

			} else {
				$pic_uri = drupal_get_path('module', 'document_presenter') . '/icons/Icos_Wall.png';
			}

			$desc = '';
			if ($file['file_desc']) {
				$desc = $file['file_desc'];

			} else {
				$desc = $file['file_name'];
			}

			$size = '';
			if ($file['file_size']) {
				$size = '(' . $file['file_size'] . ')';
			}


			if ($count < 4) {
				$output .= '<div class="post">';

				$output .= '<div class="pic">';
				$output .= '<a href="' . $folder . '/' . $file['file_name'] . '" target="_blank"><img src="' . $pic_uri . '" style="width: 200px" /></a>';
				$output .= '</div>';

				$output .= '<div class="desc">' . $desc . '</div>';

				$output .= '<div class="file">';
				$output .= '<img src="/' . drupal_get_path('module', 'document_presenter') . '/icons/application-pdf.png" />';
				$output .= '<a href="' . $folder . '/' . $file['file_name'] . '" target="_blank">Download</a>';
				$output .= '</div>';

				$output .= '</div>';

			} else {

				if ($count == 4) {
					$output .= '<br /><br />';

					$output .= '<div class="panel-group" id="document_presenter_accordion" role="tablist" aria-multiselectable="true">';
					$output .= '<div class="panel panel-default">';
					$output .= '<div class="panel-heading" role="tab" id="document_presenter_accordion_heading" style="' . $element_color . '">';
					$output .= '<h3 class="panel-title">';
					$output .= '<a role="button" data-toggle="collapse" data-parent="#document_presenter_accordion" href="#document_presenter_accordion_collapse" aria-expanded="true" aria-controls="document_presenter_accordion_collapse">';
					$output .= 'Earlier press and media';
					$output .= '</a>';
					$output .= '</h3>';
					$output .= '</div>';
					$output .= '<div id="document_presenter_accordion_collapse" class="panel-collapse collapse" role="tabpanel" aria-labelledby="document_presenter_accordion_heading">';
					$output .= '<div class="panel-body">';

					$has_archive = true;
				}

				$output .= '<div class="archive">';

				$output .= '<div class="file">';
				$output .= '<img src="/' . drupal_get_path('module', 'document_presenter') . '/icons/application-pdf.png" />';
				$output .= '<a href="' . $folder . '/' . $file['file_name'] . '" target="_blank">' . $desc . '</a>';
				$output .= '</div>';

				$output .= '</div>';
			}

			$count++;
		}


		if ($has_archive) {
			$output .= '</div>';
			$output .= '</div>';
			$output .= '</div>';
			$output .= '</div>';

		}
	}

	$output .= '</div>';


	return $output;
}


function _compare($a, $b) {
	if ($a['file_timestamp'] == $b['file_timestamp']) { return 0; }
	return ($a['file_timestamp'] > $b['file_timestamp']) ? -1 : 1;
}


function _collect($filename) {
	$list = [];
	$list['file_name'] =  $filename;

	$result_1 = db_query('
		select fm.timestamp, fm.filesize, fi.field_ingress_value
		from {file_managed} fm join {field_data_field_ingress} fi on fm.fid = fi.entity_id
		where fm.filename = :filename
		',

		array(':filename' => $filename)
	)->fetchAll();

	foreach ($result_1 as $record) {
		if ($record) {
			$list['file_timestamp'] =  $record->timestamp;
			$list['file_size'] =  $record->filesize;
			$list['file_desc'] =  $record->field_ingress_value;
		}
	}


	$result_2 = db_query('
		select o.uri
		from {file_managed} o
		where o.fid in (
			select fu.fid
			from {file_managed} fm join {file_usage} fu on fm.fid = fu.id
			where fm.filename = :filename)
		',

		array(':filename' => $filename)
	)->fetchAll();

	foreach ($result_2 as $record) {
		if ($record) { $list['file_pic_uri'] =  $record->uri; }
	}

	return $list;
}


