- include_vars: "vars/{{ ansible_distribution | lower }}.yml"

- name: Create self-signed certificate
  command: >
    openssl req -x509 -nodes -subj '/CN={{ certbot_fake_cn }}' -days 365
    -newkey rsa:4096 -sha256 -keyout {{ certbot_fake_key }}
    -out {{ certbot_fake_crt }}
  args:
    creates: "{{ certbot_fake_crt }}"

- name: Create nginx config string
  set_fact:
    certbot_nginx_conf: |
      ssl_certificate {{ certbot_fake_crt }};
      ssl_certificate_key {{ certbot_fake_key}};
