# This task can sometimes fail even though yum succeeds. The reason is that if
# another task, say via pip, has installed something that requires the urllib3
# python package, then this task will fail to install certbots urllib3
# requirement and yum will say something like "Complete! Failure!"
- name: Install Certbot for CentOS
  package: name=certbot-nginx state=present
  when: ansible_distribution == 'CentOS'

- block:
    - name: Install software-properties-common for Ubuntu
      package: name=software-properties-common state=present

    - name: Add PPA for Certbot for Ubuntu
      apt_repository: repo='ppa:certbot/certbot'

    - name: Install Certbot for Ubuntu
      package: name=python-certbot-nginx state=present
  when: ansible_distribution == 'Ubuntu'
