- name: Create .ssh/config
  blockinfile:
    create: yes
    mode: 0600
    owner: "{{ _local_user.uid }}"
    group: "{{ _local_user.group }}"
    path: "{{ remotebackup_local_config }}"
    marker: "# {mark} ansible config for host {{ remotebackup_remote_host }}"
    block: |
      Host {{ remotebackup_remote_host }}
        User {{ remotebackup_remote_user }}
        HostName {{ remotebackup_remote_ip }}

- delegate_to: "{{ remotebackup_remote_host }}"
  block:
    - name: Create remote user
      user:
        name: "{{ remotebackup_remote_user }}"
      register: _remote_user

    - name: Create remote destination
      file:
        path: "{{ remotebackup_remote_dest }}"
        state: directory
        owner: "{{ _remote_user.uid }}"
        group: "{{ _remote_user.group }}"
      register: _remote_dest

    - name: Install rsync
      package:
        name: rsync
        # On CentOS 7, rsync-3.0.2 doesn't contain the rrsync script but 3.1.2
        # does, try to get the latest version.
        state: latest

    - import_tasks: remotebackup_remote_centos.yml
      when: hostvars[remotebackup_remote_host].ansible_distribution == "CentOS"

    - import_tasks: remotebackup_remote_ubuntu.yml
      when: hostvars[remotebackup_remote_host].ansible_distribution == "Ubuntu"

    - name: Fix permissions on rrsync script
      file:
        path: "{{ remotebackup_remote_script }}"
        mode: +x

    - name: Authorize local ssh keys on remote host
      authorized_key:
        user: "{{ remotebackup_remote_user }}"
        state: present
        key: "{{ _local_user.ssh_public_key }}"
        key_options: >-
          command="{{ remotebackup_remote_script }} {{ _rrsync_opts }} {{ _remote_dest.path }}",from="{{ remotebackup_local_ip }}",no-agent-forwarding,no-port-forwarding,no-X11-forwarding

    - name: Read remote host key
      slurp:
        src: /etc/ssh/ssh_host_ecdsa_key.pub
      register: _remote_host_key


- name: Add remote host keys to local known_hosts
  known_hosts:
    path: /etc/ssh/ssh_known_hosts
    name: "{{ remotebackup_remote_ip }}"
    # Since we'll be using host names in ~/.ssh/config with an ip-number
    # provided, we must also add the host keys using ip-number otherwise it
    # won't work.
    key: "{{ remotebackup_remote_ip }} {{ _remote_host_key.content | b64decode }}"
