- name: Find rrsync script on CentOS
  shell: >-
    cp /usr/share/doc/rsync-*/support/rrsync
    {{ remotebackup_remote_script }}
  failed_when: false
  args:
    creates: "{{ remotebackup_remote_script }}"

- set_fact:
    # The rrsync script in Ubuntu _requires_ the '-wo' option, but the version
    # in CentOS doesn't have the option at all.
    _rrsync_opts:
