- name: Create local user
  user:
    name: "{{ remotebackup_local_user }}"
    generate_ssh_key: yes
  register: _local_user

- name: Create README
  blockinfile:
    create: yes
    path: "{{ remotebackup_local_readme }}"
    marker: "{mark} Overview"
    block: |
      This user has been created by ansible.
      It is used for remote backup using ssh/rsync.
      Check the {{ remotebackup_local_script }} and .ssh/config for details.

- include_tasks: remotebackup_remote.yml
  with_items: "{{ remotebackup_remote_hosts }}"
  loop_control:
    loop_var: remotebackup_remote_host

- name: Create remotebackup script
  template:
    src: remotebackup
    dest: "{{ remotebackup_local_script }}"
    mode: +x

- name: Create test file to backup
  copy:
    content: "Hello!"
    dest: "{{ _local_user.home }}/.hello"
  register: _test_file

- name: Test backup
  command: >-
    remotebackup -av {{ _test_file.dest }} .test
  register: _run
  changed_when: false
  failed_when: '("total size is %s" % _test_file.size) not in _run.stdout'
