<?php

/**
 * Configuration
 */


function broscience_style_menu() {
	$items = array();

	$items['admin/config/content/broscience_style'] = array(
			'title' => 'Broscience style',
			'description' => 'Configuration for Broscience eg. header image',
			'page callback' => 'drupal_get_form',
			'page arguments' => array('form'),
			'access arguments' => array('access administration pages'),
			'type' => MENU_NORMAL_ITEM,
	);

	return $items;
}

function form($form, &$form_state) {
	
	/**
	 * broscience_style_header
	 **/
	$form['broscience_style_header'] = array(
			'#type' => 'fieldset',
			'#title' => t('Header'),
			'#description' => t('The background image actually consists of three images - large, medium and small size.<br/>The large size should be over 2000 * 200 pixels. The medium size should be half of the large and the small size half the medium.<br/><br/>'),
			'#collapsible' => FALSE,
			'#collapsed' => FALSE,
	);	

	$image = '';
	$imageDesc = 'not defind yet';
	if (variable_get('broscience_style_header_image')) {
		$image = variable_get('broscience_style_header_image');
		$imageDesc = $image;
	}
	
	$form['broscience_style_header']['broscience_style_header_image'] = array(
			'#type' => 'textfield',
			'#title' => t('Assign an URL for the LARGE image.'),
			'#description' => t('Current image is ' . $imageDesc . '.'),
			'#required' => FALSE,
			'#default_value' => $image,
	);
	
	$imageMedium = '';
	$imageMediumDesc = 'not defind yet';
	if (variable_get('broscience_style_header_image_medium')) {
		$imageMedium = variable_get('broscience_style_header_image_medium');
		$imageMediumDesc = $imageMedium;
	}
	
	$form['broscience_style_header']['broscience_style_header_image_medium'] = array(
			'#type' => 'textfield',
			'#title' => t('Assign an URL for the MEDIUM image.'),
			'#description' => t('Current image is ' . $imageMediumDesc . '.'),
			'#required' => FALSE,
			'#default_value' => $imageMedium,
	);	
	
	$imageSmall = '';
	$imageSmallDesc = 'not defind yet';
	if (variable_get('broscience_style_header_image_small')) {
		$imageSmall = variable_get('broscience_style_header_image_small');
		$imageSmallDesc = $imageSmall;
	}
	
	$form['broscience_style_header']['broscience_style_header_image_small'] = array(
			'#type' => 'textfield',
			'#title' => t('Assign an URL for the SMALL image.'),
			'#description' => t('Current image is ' . $imageSmallDesc . '.'),
			'#required' => FALSE,
			'#default_value' => $imageSmall,
	);	

	$tint = '';
	$tintDesc = 'not defind yet';
	if (variable_get('broscience_style_header_tint')) {
		$tint = variable_get('broscience_style_header_tint');
		$tintDesc = $tint;
	}
	
	$form['broscience_style_header']['broscience_style_header_tint'] = array(
			'#type' => 'textfield',
			'#title' => t('Assign a RGBA color value as a layer over the header image.'),
			'#description' => t('Format eg. 240, 99, 34, 0.3'),
			'#required' => FALSE,
			'#default_value' => $tint,
	);
	
	$logoPadding = '';
	if (variable_get('broscience_style_logo_padding')) {
		$logoPadding = variable_get('broscience_style_logo_padding');
	}
	
	$form['broscience_style_header']['broscience_style_header_logo_padding'] = array(
			'#type' => 'textfield',
			'#title' => t('Assign a value for padding the top and the bottom for the logo.'),
			'#description' => t('The logo image can be set in the theme administration.'),
			'#required' => FALSE,
			'#default_value' => $logoPadding,
	);	
	
	/**
	 * broscience_style_menu
	 **/
	 $form['broscience_style_menu'] = array(
			'#type' => 'fieldset',
			'#title' => t('Menu'),
			'#description' => t(''),
			'#collapsible' => FALSE,
			'#collapsed' => FALSE,
	);
	
	$menuButtonColor = '';
	if (variable_get('broscience_style_menu_button_color')) {
		$menuButtonColor = variable_get('broscience_style_menu_button_color');
	}
	
	$form['broscience_style_menu']['broscience_style_menu_button_color'] = array(
			'#type' => 'textfield',
			'#title' => t('Assign a color value for the active/hovered button in the menu.'),
			'#description' => t('Format eg. #F06322'),
			'#required' => FALSE,
			'#default_value' => $menuButtonColor,
	);

	$use2LevelSubMenu = '';
	if (variable_get('broscience_style_menu_use_2level_submenu')) {
		$use2LevelSubMenu = variable_get('broscience_style_use_2level_submenu');
	}
			
	$form['broscience_style_menu']['broscience_style_menu_use_2level_submenu'] = array(
			'#type' => 'checkbox',
			'#title' => t('Made use of a two level submenu.'),
			'#description' => t('If selected make sure there is a menu-block with starting level at two and maximum depth with two.'),
			'#required' => FALSE,
			'#default_value' => $use2LevelSubMenu,
	);	
	
	$hideH2 = '';
	if (variable_get('broscience_style_menu_hide_h2')) {
		$hideH2 = variable_get('broscience_style_menu_hide_h2');
	}
				
	$form['broscience_style_menu']['broscience_style_menu_hide_h2'] = array(
			'#type' => 'checkbox',
			'#title' => t('Hide main menu element names.'),
			'#description' => t('If a selected item in the main menu has submenus the name of the menu item will show up in a big way.'),
			'#required' => FALSE,
			'#default_value' => $hideH2,
	);	
	
	
	/**
	 * titleColor
	 **/
	$titleColor = '';
	if (variable_get('broscience_style_title_color')) {
		$titleColor = variable_get('broscience_style_title_color');
	}
	
	$form['broscience_style_title_color'] = array(
			'#type' => 'textfield',
			'#title' => t('Assign a color value for the title of the page.'),
			'#description' => t('Format eg. #F06322'),
			'#required' => FALSE,
			'#default_value' => $titleColor,
	);

	return system_settings_form($form);
}
