#!/bin/sh
# ss(1) is frivolous with whitespace which makes output hard to read. This
# script will compress the column-separating whitespace when printing to a
# terminal.

if [ -t 1 ]; then
    exec /bin/ss "$@" | column -t
else
    exec /bin/ss "$@"
fi
