<?php
/**
 * @file
 * Code for the ICOS Media feature.
 */

include_once 'icos_media_feature.features.inc';

/**
 * Implements hook_field_extra_fields().
 *
 * Add the File name as an extra field.
 *
 * @return mixed
 */
function icos_media_feature_field_extra_fields() {
  $extra ['file']['icos_document'] = array(
    'display' => array(
      'icos_file_name' => array(
        'label' => t('File name'),
        'description' => t('The name of the file.'),
        'weight' => 0,
      ),
    )
  );

  return $extra;
}

/**
 * Implements hook_entity_view().
 *
 * Output the file name.
 *
 * @param $entity
 * @param $type
 * @param $view_mode
 * @param $langcode
 */
function icos_media_feature_entity_view($entity, $type, $view_mode, $langcode) {
  if ($type == 'file' && $entity->type == 'icos_document') {
    $extra_fields = field_extra_fields_get_display($type, $entity->type, $view_mode);
    if (!empty($extra_fields['icos_file_name']) && $extra_fields['icos_file_name']['visible'] == true) {
      $entity->content['icos_file_name'] = array(
        '#weight' => $extra_fields['icos_file_name']['weight'],
        '#markup' => '<div class="field-icos-file-name">' . $entity->filename . '</div>'
      );
    }
  }
}