# This Makefile serves as a place to keep commands that are useful when
# maintaining the stiltweb app. To try it, use 'make status'.

status:
	systemctl {{ stiltweb_servicename }}

watch:
	{{ stiltweb_bin_dir }}/tail-latest.sh

syncnames:
	{{ stiltweb_bin_dir }}/sync-station-names.sh

