# This Makefile serves as a place to keep commands that are useful when
# maintaining the stiltweb app. To try it, use 'make status'.

status:
	systemctl {{ stiltweb_servicename }}

watch:
	{{ stiltweb_bin_dir }}/tail-latest.sh

syncnames:
	{{ stiltweb_bin_dir }}/sync-station-names.sh

sync-fsicos1-to-fsicos2:
	{{ stiltweb_bin_dir }}/sync-fsicos1-to-fsicos2.sh

bulk-create-csv-files:
	echo please run	{{ stiltweb_bin_dir }}/bulk-create-csv-files.py

sync-stilt-to-stiltweb:
	echo please run {{ stiltweb_bin_dir }}/sync-stilt-to-stiltweb.py
