- name: Run the jarservice role
  import_role:
    name: icos.jarservice
  vars:
    username        : "{{ stiltcluster_username }}"
    extra_groups    : docker
    jarfile         : "{{ stiltcluster_jar_file }}"
    servicename     : "{{ stiltcluster_servicename }}"
    servicetemplate : "{{ stiltcluster_template }}"
    apptemplate     : "{{ stiltcluster_apptemplate }}"
  when: stiltcluster_jar_file is defined

- name: Add stiltweb key to authorized_keys
  authorized_key:
    user: "{{ stiltcluster_username }}"
    state: present
    key: "{{ lookup('file', 'roles/icos.stiltweb/files/stiltweb.pub') }}"

- name: Create bin directory
  file:
    path: "{{ stiltcluster_bin_dir }}"
    state: directory

- name: Install scripts
  template:
    src:   "{{ item }}.j2"
    dest:  "{{ stiltcluster_bin_dir }}/{{ item }}"
    owner: "{{ stiltcluster_username }}"
    group: "{{ stiltcluster_username }}"
    mode:  0755
  with_items:
    - remove-old-stiltruns.sh

- name: Add the remove-old-stiltruns cron job
  cron:
    name: remove old stiltruns
    job: "$HOME/bin/remove-old-stiltruns.sh"
    minute: 22
    user: "{{ stiltcluster_username }}"
