<?php


function alfresco_reader_block_info() {
	$blocks = array();
	
	$blocks['alfresco_reader'] = array(
			'info' => t('Alfresco reader'),
	);

	return $blocks;
}


function alfresco_reader_block_view($delta = '') {

	if ($delta == 'alfresco_reader') {

		$folderIdList = array();
		$objectIdList = '';
		if (variable_get('alfresco_reader_objectid_list')) {
			$folderIdList = explode(',', variable_get('alfresco_reader_objectid_list'));
		}
		
		
		$title_color = '';
		if (variable_get('broscience_style_contents_title_color')) {
			$title_color = 'style="color: ' . variable_get('broscience_style_contents_title_color') . '"';
		}
		
		$output = '<div class="block_title" ' . $title_color . '><h2>DOCUMENTS</h2></div>';
		
		foreach ($folderIdList as $folderId) {
			$id = trim($folderId);
			if (! empty($id)) {
				$properties = _alfresco_reader_get_cmis_object_properties($id);
				$contents = _alfresco_reader_get_cmis_sub_objects($id);
				$output .= _alfresco_reader_output($properties, $contents);
			}
		}
 
		$block = array(
			'subject' => t(''),
			'content' => array(
				'#markup' => t($output),
				'#attached' => array(
					'css' => array('https://static.icos-cp.eu/constant/bootstrap/3.3.4/css/bootstrap.min.css', drupal_get_path('module', 'alfresco_reader') . '/alfresco_reader.css'),
					'js' => array('https://static.icos-cp.eu/constant/jquery/1.11.2/jquery.min.js', 'https://static.icos-cp.eu/constant/bootstrap/3.3.4/js/bootstrap.min.js', drupal_get_path('module', 'alfresco_reader') . '/alfresco_reader.js'),
				),
			),
		);
		
		return $block;
	}

}


function _alfresco_reader_output($properties, $contents) {

	$element_color = '';
	if (variable_get('broscience_style_contents_element_color')) {
		$element_color = 'background-color: ' . variable_get('broscience_style_contents_element_color') . '; color: #ffffff;';
	}

	$icon = '';
	// ATC
	if ($properties->properties['cmis:objectId'] == '0ecc91a5-7479-4df2-97a5-d2d99b6a6737') {
		$icon = '<img src="/' . drupal_get_path('module', 'alfresco_reader') . '/icons/icon_cloud_atc.svg" />';

	// ETC
	} else if ($properties->properties['cmis:objectId'] == '608af1f2-28f2-4ee7-b220-42784d53938e') {
		$icon = '<img src="/' . drupal_get_path('module', 'alfresco_reader') . '/icons/icon_leaf_etc.svg" />';

	// OTC
	} else if ($properties->properties['cmis:objectId'] == 'f078f032-e65c-4b5e-92ca-9207f9acee08') {
		$icon = '<img src="/' . drupal_get_path('module', 'alfresco_reader') . '/icons/icon_wave_otc.svg" />';

	// CP
	} else if ($properties->properties['cmis:objectId'] == 'fad26865-2095-46d0-b0b4-a0d3feaddc23') {
		$icon = '<img src="/' . drupal_get_path('module', 'alfresco_reader') . '/icons/icon_database_cp.svg" />';

	// CAL
	} else if ($properties->properties['cmis:objectId'] == '13094ca8-a799-479d-8123-a53bc8679b2b') {
		$icon = '<img src="/' . drupal_get_path('module', 'alfresco_reader') . '/icons/icon_graph_cal.svg" />';

	}


	$output = '<div id="alfresco_reader_accordion_' . $properties->properties['cmis:objectId'] . '" class="alfresco_reader panel-group" role="tablist" aria-multiselectable="true">';

	$output .= '<div class="panel panel-default">';
	
	$output .= '<div id="alfresco_reader_accordion_heading_' . $properties->properties['cmis:objectId'] .'" class="panel-heading" role="tab" style="' . $element_color . '">';
	$output .= '<h3 class="panel-title">';
	$output .= '<a role="button" data-toggle="collapse" data-parent="#alfresco_reader_accordion_' . $properties->properties['cmis:objectId'] . '" href="#alfresco_reader_accordion_collapse_'. $properties->properties['cmis:objectId'] . '" aria-expanded="true" aria-controls="alfresco_reader_accordion_collapse_' . $properties->properties['cmis:objectId'] . '">';
	$output .= $properties->properties['cmis:name'];
	$output .= '</a>';

	$output .= $icon;

	$output .= '</h3>';
	$output .= '</div>';
	
	$output .= '<div id="alfresco_reader_accordion_collapse_' . $properties->properties['cmis:objectId'] . '" class="panel-collapse collapse" role="tabpanel" aria-labelledby="alfresco_reader_accordion_heading_' . $properties->properties['cmis:objectId'] . '">';

	$output .= '<div class="panel-body">';

	$output .= '<table class="table table-hover table-responsive">';

	foreach ($contents as $content) {
		if ($content->properties['cmis:baseTypeId'] != 'cmis:folder') {
			$document = trim($content->properties['cmis:name']);
			$document = str_replace('_', ' ', $document);

			$modifiedBy = $content->properties['cmis:lastModifiedBy'];
			$modifiedBy = str_replace('.', ' ', $modifiedBy );

			$modificationDate = new DateTime($content->properties['cmis:lastModificationDate']);

			$output .= '<tr>';
			$output .= '<td>';
			
			$output .= l($document, 'cmis/browser', array('query' => array('id' => $content->properties['cmis:objectId'])));
			$output .= '<br/>';
			$output .= '<span class="small_text">' . $modifiedBy . '  ' . $modificationDate->format('Y-m-d H:i') . '</span>';
			
			$output .= '</td>';
			$output .= '</tr>';
		}		
	}	
	
	$output .= '</table>';
	
	$output .= '</div>';
	$output .= '</div>';
	$output .= '</div>';
	$output .= '</div>';
	
	return $output;
}


function _alfresco_reader_get_cmis_object_properties($objectId) {
	module_load_include('api.inc', 'cmis');
	
	try {
		$repository = cmisapi_getRepositoryInfo();
		$properties = cmisapi_getProperties($repository->repositoryId, $objectId);

		return $properties;		

	} catch (CMISException $e) {
		cmis_error_handler('cmis_query', $e);
	}	
}


function _alfresco_reader_get_cmis_sub_objects($objectId) {
	module_load_include('api.inc', 'cmis');

	try {
		$repository = cmisapi_getRepositoryInfo();
		$repoId = !empty ($repository->repositoryId) ? $repository->repositoryId : 'default';	
		$objects = cmisapi_getChildren($repoId, $objectId)->objectList;

		return $objects;
		
	} catch (CMISException $e) {
		cmis_error_handler('cmis_query', $e);
	}		
}


function alfresco_reader_menu() {
	$items = array();

	$items['admin/config/content/alfresco_reader'] = array(
			'title' => 'Alfresco reader configuration',
			'description' => 'Configuration for Alfresco reader',
			'page callback' => 'drupal_get_form',
			'page arguments' => array('_alfresco_reader_form'),
			'access arguments' => array('access administration pages'),
			'type' => MENU_NORMAL_ITEM,
	);

	return $items;
}


function _alfresco_reader_form($form, &$form_state) {

	$objectIdList = '';
	if (variable_get('alfresco_reader_objectid_list')) {
		$objectIdList = variable_get('alfresco_reader_objectid_list');
	}
	
	$form['alfresco_reader_objectid_list'] = array(
			'#type' => 'textarea',
			'#title' => t('Assign a comma separated list of folder id\'s.'),
			'#description' => t('Insert a comma separated list of id\'s of the Alfresco folders you want to list contents from.<br/>If there are some issues you will be noticed when you display the page.'),
			'#required' => FALSE,
			'#default_value' => $objectIdList,
	);

	return system_settings_form($form);
}
