---
- name: Create ssh directory
  file:
    path: "{{ project_dir }}/.ssh"
    state: directory

- name: Copy SSH public key
  copy:
    src: id_rsa.pub
    dest: "{{ project_dir }}/.ssh/"
    mode: 0644

- name: Copy SSH private key
  copy:
    src: id_rsa
    dest: "{{ project_dir }}/.ssh/"
    mode: 0600

- name: Check if known_hosts contains bitbucket
  command: ssh-keygen -F bitbucket.org
  register: bitbucket_known_hosts
  failed_when: false
  changed_when: false

- name: Update bitbucket known hosts
  known_hosts:
    name: bitbucket.org
    key: "{{ lookup('pipe', 'ssh-keyscan bitbucket.org, `dig +short bitbucket.org`') }}"
  when: bitbucket_known_hosts.stdout == ""
