# <2017-01-16 mån> Installing 'docker-engine' instead of the default
# 'docker'. The reason is that 'docker' didn't work properly out of the box -
# the client couldn't reach the daemon due to (I think) a socket mishap.
- name: Add the official docker repository
  yum_repository:
    name: docker
    description: Offical Docker RPM repository
    enabled: yes
    baseurl: https://yum.dockerproject.org/repo/main/centos/7/
    gpgcheck: yes
    gpgkey: https://yum.dockerproject.org/gpg

- name: Add the EPEL repo
  yum: name=epel-release state=present

- name: Install docker
  package:
    name={{ item }} state=present
  with_items:
    - docker-engine
    - docker-compose
    - python-pip

- name: Install docker-compose python module
  pip:
    name: "{{ item }}"
    state: present
  loop:
    - docker
    - docker-compose
