version: '2'
services:
  kanboard:
    image: kanboard/kanboard:latest
    ports:
     - "127.0.0.1:8099:80"
    volumes:
     - /disk/data/kanboard/data:/var/www/app/data
    restart: unless-stopped

