- import_role: name=icos.certbot

- name: Run the jarservice role
  import_role:
    name: icos.jarservice
  vars:
    username        : "{{ cpdata_username }}"
    jarfile         : "{{ cpdata_jar_file }}"
    # https://github.com/ansible/ansible/issues/20597
    apptemplate     : roles/icos.cpdata/templates/application.conf.j2
    nginxconfig     : "{{ cpdata_nginxconfig }}"
    servicename     : "{{ cpdata_servicename }}"
    servicetemplate : "{{ cpdata_template }}"
