# Provision a server to run Stiltweb (https://github.com/ICOS-Carbon-Portal/stiltweb)
---
- become: true
  hosts: all
  tasks:
    - name: Add stiltweb user
      user:
        name: stiltweb

    - name: Install JAR and config
      copy: dest=/home/stiltweb/ src={{ item }} owner=stiltweb group=stiltweb
      with_items:
        # - "{{ stiltweb_app_conf }}"
        - "{{ stiltweb_jar_file }}"
      notify: restart stiltweb

    - name: Create JAR symlink
      file:
        src: "/home/stiltweb/{{ stiltweb_jar_file | basename}}"
        dest: /home/stiltweb/stiltweb.jar
        state: link
        
    - name: Add systemd stiltweb.service
      copy: src=stiltweb.service dest=/etc/systemd/system/stiltweb.service

    - name: Enable systemd stiltweb service
      service: name=stiltweb state=started enabled=yes

    - name: Add nginx config file
      copy: src=stiltweb.conf dest=/etc/nginx/conf.d/
      notify: reload nginx config 

  handlers:
    - name: restart stiltweb
      service: name=stiltweb state=restarted

    - name: reload nginx config
      service: name=nginx state=reloaded

      
