FROM cd65ca564e63b33f4f037464f2fb55160c9ed686a93684e6dbdfb8821d7ebfb5

#===========SET UP TEST CASE==============================================================

COPY ./changes/* /opt/STILT_modelling/
COPY ./changes/stiltR/* /opt/STILT_modelling/stiltR/
