FROM python:{{ geoip_python_version }}

RUN pip install pipenv

COPY repo/src/main/python/geoip /geoip
COPY config.py /geoip/py/config.py

WORKDIR /geoip
RUN pipenv install --deploy
CMD  ["pipenv", "run", "gunicorn", "--bind", "0.0.0.0:5000", "wsgi"]
