#!/bin/bash
# Shut down service. Do backup. Start service again.

set -Eueo pipefail

if [[ ! -f docker-compose.yml ]]; then
   echo "Expected to find docker-compose.yml here."
   exit 1
fi

if [[ ! -d volumes ]]; then
    echo "Expected to find volumes directory here."
    exit 1
fi

if [[ ! -x "bin/bbclient-all" ]]; then
    echo "Could not execute bin/bbclient-all"
    exit 1
fi

if [[ -z "${1:-}" ]]; then
    ARCHIVE="test-{now}"
else
    ARCHIVE="$1-{now}"
fi


BUILD_INFO=$PWD/volumes/build.info
# If our docker-builds script is available then dump information about
# currently running images.
if [[ -f build.log ]]; then
    docker-builds > "$BUILD_INFO" || :
fi

# Do 'docker-compose up' as part of that trap so that we the service
# resume even if the backup fails.
trap 'rm -f "$BUILD_INFO"; docker-compose up -d' EXIT

docker-compose down

export BORG_UNKNOWN_UNENCRYPTED_REPO_ACCESS_IS_OK=yes

(echo -n '=== starting backup '; date;
 "bin/bbclient-all" create --verbose --stats "::$ARCHIVE" volumes 2>&1) \
    | tee -a backup.log || :

