#!/bin/bash
# Shut down service. Do backup. Start service again.
# Designed to run from cron.

set -Eueo pipefail

if [[ ! -f docker-compose.yml ]]; then
   echo "Expected to find docker-compose.yml here."
   exit 1
fi

if [[ ! -d volumes ]]; then
    echo "Expected to find volumes directory here."
    exit 1
fi

if [[ ! -x "bin/bbclient-all" ]]; then
    echo "Could not execute bin/bbclient-all"
    exit 1
fi

if [[ -z "${1:-}" ]]; then
    ARCHIVE="test-{now}"
else
    ARCHIVE="$1-{now}"
fi


BUILD_INFO=$PWD/volumes/build.info
# If our docker-builds script is available then dump information about
# currently running images.
if [[ -f build.log ]]; then
    docker-builds > "$BUILD_INFO" || :
fi

# Do 'docker-compose up' as part of that trap so that the service resume even
# if the backup fails.
trap 'rm -f -- "$BUILD_INFO"; docker-compose up -d >& /dev/null' EXIT

docker-compose down >& /dev/null

export BORG_UNKNOWN_UNENCRYPTED_REPO_ACCESS_IS_OK=yes

LOGFILE=backup.log
HEADER="=== starting backup"

echo "$HEADER $(date)" >> "$LOGFILE"

# By default we generate no output, as not to spook cron.
if ! bin/bbclient-all create \
     "::$ARCHIVE" volumes >> "$LOGFILE" 2>&1
then
    # In case of error, output everything after the last header.
    sed -n ":a;\$p;N;/$HEADER/d;ba" "$LOGFILE"
    exit 1
fi

