- name: Copy database dump
  copy:
    src: "{{ backup_path }}/{{ project_name }}Drupal/db/"
    dest: "{{ project_dir }}/db/"

- name: Wait 10 seconds for the database daemon to start
  wait_for: timeout=10

- name: Restore database
  shell:
    >
    docker exec -i {{ project_name }}_mariadb_1 sh -c
    'mysql -u root -p"$MYSQL_ROOT_PASSWORD" -e "DROP DATABASE IF EXISTS {{ database_name | default("icos") }}; CREATE DATABASE {{ database_name | default("icos") }}"
    && mysql -u root -p"$MYSQL_ROOT_PASSWORD" {{ database_name | default("icos") }} < /var/lib/mysql/{{ project_name }}_db_dump.sql'
  # mysql is not always ready to accept connections the first time
  register: result
  until: result.stderr == ""
  retries: 3
  delay: 5
